
FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y vim git pip libgl1 libglib2.0-0 

RUN apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

RUN pip install tensorflow[and-cuda] flask

WORKDIR /home/ubuntu

RUN git clone --recursive https://github.com/skvark/opencv-python.git

WORKDIR ./opencv-python

RUN export CMAKE_ARGS="-DWITH_GSTREAMER=ON"

RUN pip install --upgrade pip wheel

RUN pip wheel . --verbose

RUN pip install opencv_python*.whl

WORKDIR /home/ubuntu

RUN rm -rf opencv-python

RUN git clone https://github.com/lefmylonas/human_detection.git

EXPOSE 5001

EXPOSE 8002

WORKDIR /home/ubuntu/human_detection/tf_example

CMD ["python3", "gstreamer_udp_stream_web.py"]
